// Signed local HTTP + WebSocket execution of production voice composition.
// Google/Twilio identities are synthetic; SDK network clients never connect.
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import assert from 'node:assert/strict';import express from 'express';import {once,EventEmitter} from 'node:events';import WebSocket from 'ws';import twilio from 'twilio';import {spawnSync} from 'node:child_process';
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'SYNTHETIC-phone-audit-'));
Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:path.join(temporary,'synthetic.sqlite'),PRICEBOOK_PATH:path.join(temporary,'books'),APP_DATA_DIR:temporary,ALLOW_PROVIDER_WRITES:'false',VOICE_RUNTIME_ENABLED:'false',STRIPE_BILLING_ENABLED:'false',JWT_SECRET:'SYNTHETIC_PHONE_KEY_DO_NOT_USE'.padEnd(64,'x')});
const {db,ownerQuery,migrate}=await import('../../server/src/db.js');migrate();
const {installProductionVoice}=await import('../../server/src/voice/productionVoiceRuntime.js');
const {createOwnerCallService}=await import('../../server/src/ownerCallService.js');
const {createVoiceSessionStore}=await import('../../server/src/voice/voicePersistence.js');
const {createGeminiMediaBridge}=await import('../../server/src/voice/geminiMediaBridge.js');
const service=createOwnerCallService({ownerQuery}),results=[];
const AT='2026-10-06T12:00:00.000Z',ACCOUNT='AC'+'b'.repeat(32),TOKEN='SYNTHETIC_CALLBACK_AUTH_NOT_LIVE',ORIGIN='https://synthetic-voice.example.invalid';let serial=50;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(predicate){const deadline=Date.now()+3000;while(!predicate()){if(Date.now()>deadline)throw Error('Synthetic wait timed out');await delay(5);}}
async function experiment(id,expected,fn){try{const {meetsExpectation,actual}=await fn();results.push({id,expected,meetsExpectation,actual});console.log(id,meetsExpectation?'PASS':'EXPECTATION MISMATCH');}catch(error){results.push({id,expected,experimentError:{message:error.message,stack:error.stack}});console.log(id,'EXPERIMENT ERROR',error.message);}}
async function harness({failOpen=false}={}){
 const id=serial++,owner='synthetic-phone-'+id,from='+19025550100',to='+19025550'+String(100+id),fallback='+19025550199',callSid='CA'+id.toString(16).padStart(32,'0'),streamSid='MZ'+id.toString(16).padStart(32,'0');
 db.prepare("INSERT INTO users(id,email,passwordHash,firstName,businessName,plan,planStatus,timezone,role,createdAt) VALUES(?,?,'[SYNTHETIC]','Synthetic','Synthetic phone company','Operator','active','UTC','owner',?)").run(owner,owner+'@example.invalid',AT);
 db.prepare('INSERT INTO billingAccounts(ownerId,stripeCustomerId,paymentMethodVerifiedAt,createdAt,updatedAt) VALUES(?,?,?,?,?)').run(owner,'cus_SYNTHETIC_'+id,AT,AT,AT);db.prepare("UPDATE users SET planStatus='active' WHERE id=?").run(owner);
 db.prepare("INSERT INTO businessProfiles(ownerId,existingPhoneNumber,twilioNumber,twilioNumberSid,phoneProvisioningStatus,operatorEnabled,agentName,knowledgeBaseJson,updatedAt) VALUES(?,?,?,?,'provisioned',1,'Synthetic Assistant',?,?)").run(owner,fallback,to,'PN_SYNTHETIC_'+id,JSON.stringify({about:'Synthetic repairs',hours:'Synthetic hours'}),AT);
 let callbacks,providerSent=[],providerOpens=0;const errors=[],responses=new Map(),attempts={sms:0,transfer:0,notify:0};
 const googleClient={live:{connect:async input=>{providerOpens++;callbacks=input.callbacks;if(failOpen)throw Error('[SYNTHETIC] provider failure with private caller details');return {sendRealtimeInput:async()=>{},sendClientContent:input=>providerSent.push(input),sendToolResponse:async input=>{for(const response of input.functionResponses)responses.set(response.id,response.response);},close:async()=>{}};}}};
 const app=express(),voice=installProductionVoice({app,database:db,runtimeConfig:{voiceRuntime:true,providerWrites:true},env:{TWILIO_ACCOUNT_SID:ACCOUNT,TWILIO_AUTH_TOKEN:TOKEN,PUBLIC_BASE_URL:ORIGIN,GEMINI_MODEL:'synthetic-live-model',JWT_SECRET:process.env.JWT_SECRET},googleClient,clock:()=>new Date(AT),onError:code=>errors.push(code)});
 const server=app.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port,context={ownerId:owner,accountSid:ACCOUNT,callSid,from,to};let ws;
 async function post(route,patch={}){const body={AccountSid:ACCOUNT,CallSid:callSid,From:from,To:to,Direction:'inbound',...patch};return fetch(base+route,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','x-twilio-signature':twilio.getExpectedTwilioSignature(TOKEN,ORIGIN+route,body)},body:new URLSearchParams(body)});}
 async function connect(){const r=await post('/api/twilio/voice/incoming',{ownerId:'synthetic-wrong-owner'});assert.equal(r.status,200);const xml=await r.text(),url=xml.match(/<Stream url="([^"]+)"/)[1],fallbackPath=new URL(xml.match(/<Redirect method="POST">([^<]+)<\/Redirect>/)[1]).pathname;
  ws=new WebSocket(base.replace('http:','ws:')+new URL(url).pathname,{headers:{'x-twilio-signature':twilio.getExpectedTwilioSignature(TOKEN,url,{})}});await once(ws,'open');
  ws.send(JSON.stringify({event:'connected',protocol:'Call',version:'1.0.0'}));ws.send(JSON.stringify({event:'start',sequenceNumber:'1',streamSid,start:{accountSid:ACCOUNT,callSid,streamSid,tracks:['inbound'],mediaFormat:{encoding:'audio/x-mulaw',sampleRate:8000,channels:1}}}));await until(()=>!!callbacks);await delay(15);return {xml,fallbackPath,streamUrl:url};}
 async function tool(name,args,id=crypto.randomUUID()){callbacks.onmessage({toolCall:{functionCalls:[{name,args,id}]}});await until(()=>responses.has(id));return responses.get(id);}
 async function transcript(text){callbacks.onmessage({serverContent:{inputTranscription:{text}}});await until(()=>db.prepare('SELECT transcriptJson FROM calls WHERE ownerId=? AND callSid=?').get(owner,callSid)?.transcriptJson.includes(text));}
 async function stop(){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({event:'stop',sequenceNumber:'2',streamSid,stop:{accountSid:ACCOUNT,callSid}}));await until(()=>db.prepare('SELECT status FROM calls WHERE ownerId=? AND callSid=?').get(owner,callSid)?.status==='COMPLETED');}
 async function close(){ws?.terminate();await voice.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
 return {owner,context,post,connect,tool,transcript,stop,close,errors,get providerOpens(){return providerOpens;},get callbacks(){return callbacks;},get ws(){return ws;}};
}
try{
 await experiment('E21','Provider-start failure offers durable actionable lead and owner alert, with no audio storage.',async()=>{const h=await harness({failOpen:true});try{const connected=await h.connect();await until(()=>h.ws.readyState===WebSocket.CLOSED);const r=await h.post(connected.fallbackPath),xml=await r.text();const row=db.prepare('SELECT id,status,transcriptJson FROM calls WHERE ownerId=? AND callSid=?').get(h.owner,h.context.callSid),detail=service.detail({ownerId:h.owner,id:row.id});return {meetsExpectation:detail.leads.length>0,actual:{http:r.status,xml,callStatus:row.status,transcript:detail.transcript,leadCount:detail.leads.length,errorCodes:h.errors,outboxCount:db.prepare('SELECT COUNT(*) n FROM outboxEvents WHERE ownerId=?').get(h.owner).n}};}finally{await h.close();}});
 await experiment('E22','Production-composed voice sends transactional SMS and transfers through implemented adapters.',async()=>{const h=await harness();try{await h.connect();const lead=await h.tool('captureLead',{name:'[SYNTHETIC] Phone lead',notes:'[SYNTHETIC] repair gate'}),sms=await h.tool('sendSms',{template:'callback',recordHandle:lead.leadHandle}),transfer=await h.tool('transferCall',{reason:'caller_requested',customerConfirmed:true});return {meetsExpectation:sms.status==='sent'&&transfer.status==='transferred',actual:{lead,sms,transfer,outbox:db.prepare('SELECT eventType,status FROM outboxEvents WHERE ownerId=?').all(h.owner),errors:h.errors}};}finally{await h.close();}});
 await experiment('E23','Real completed lead call has semantic LEAD outcome, summary and urgency; duplicate/resume callbacks cannot overwrite successful outcome.',async()=>{const h=await harness();try{const connected=await h.connect();await h.transcript('[SYNTHETIC] My kitchen is flooding; call me back.');await h.tool('captureLead',{name:'[SYNTHETIC] Flooding customer'});await h.tool('flagUrgent',{reason:'flooding',summary:'[SYNTHETIC] Flooding kitchen'});await h.stop();const row=db.prepare('SELECT id FROM calls WHERE ownerId=? AND callSid=?').get(h.owner,h.context.callSid),before=service.detail({ownerId:h.owner,id:row.id});const r=await h.post(connected.fallbackPath);const xml=await r.text(),after=service.detail({ownerId:h.owner,id:row.id});return {meetsExpectation:before.outcome==='LEAD'&&!!before.summaryText&&before.urgency&&after.outcome===before.outcome,actual:{before:{status:before.status,outcome:before.outcome,summary:before.summaryText,urgency:before.urgency,transcript:before.transcript,leads:before.leads.length},fallbackResponse:xml,after:{status:after.status,outcome:after.outcome,failureCode:after.failureCode},ownerMappedCorrectly:after.leads.every(lead=>lead.callId===row.id)}};}finally{await h.close();}});
 await experiment('E34','Consumed nonce cannot reopen a completed voice call from the public signed WebSocket boundary.',async()=>{const h=await harness();let retry;try{const connected=await h.connect();await h.stop();const status=await new Promise((resolve,reject)=>{const original=new URL(connected.streamUrl);retry=new WebSocket('ws://127.0.0.1:'+h.ws.url.match(/:(\d+)\//)[1]+original.pathname,{headers:{'x-twilio-signature':twilio.getExpectedTwilioSignature(TOKEN,connected.streamUrl,{})}});retry.on('unexpected-response',(_req,response)=>{response.resume();resolve(response.statusCode);});retry.on('open',()=>resolve(101));retry.on('error',reject);});return {meetsExpectation:status===403,actual:{reconnectStatus:status}};}finally{retry?.terminate();await h.close();}});
 await experiment('E24','Restart reconciles stranded active calls into recoverable failed/missed-call leads.',async()=>{const h=await harness();try{await h.connect();await h.transcript('[SYNTHETIC] Restart request before contact tool');const row=db.prepare('SELECT id FROM calls WHERE ownerId=? AND callSid=?').get(h.owner,h.context.callSid);const persisted=db.prepare('SELECT status FROM calls WHERE id=?').get(row.id);const crash=path.join(temporary,'crash-snapshot.sqlite');await db.backup(crash);const child=spawnSync(process.execPath,['--input-type=module','-e',"import {db} from './server/src/db.js';import {lifecycle} from './server/src/server.js';await new Promise(resolve=>setTimeout(resolve,100));console.log('RESTART_EVIDENCE '+JSON.stringify(db.prepare('SELECT status,outcome,failureCode FROM calls WHERE id=?').get(process.env.SYNTHETIC_CALL_ID)));await lifecycle.shutdown({timeoutMs:3000,exit:()=>{}});"],{cwd:new URL('../..',import.meta.url).pathname,env:{...process.env,PORT:'0',DATABASE_PATH:crash,SYNTHETIC_CALL_ID:row.id,TWILIO_ACCOUNT_SID:'',TWILIO_AUTH_TOKEN:'',GEMINI_API_KEY:'',PUBLIC_BASE_URL:'',LOCAL_PREVIEW_MODE:'false'},encoding:'utf8'});assert.equal(child.status,0,child.stderr);const restarted=JSON.parse(child.stdout.split('\n').find(line=>line.startsWith('RESTART_EVIDENCE ')).slice('RESTART_EVIDENCE '.length));return {meetsExpectation:!['CONNECTING','CONNECTED'].includes(restarted.status),actual:{persisted,restarted,leadCount:db.prepare('SELECT COUNT(*) n FROM leads WHERE callId=?').get(row.id).n}};}finally{await h.close();}});
 await experiment('E25','A queued final customer transcript is persisted before session-end telemetry.',async()=>{
  class Socket extends EventEmitter{readyState=1;bufferedAmount=0;send(_v,cb){cb?.();}close(){this.readyState=3;}}
  const socket=new Socket(),stored=[];let callbacks;const bridge=createGeminiMediaBridge({openGeminiSession:async input=>{callbacks=input.callbacks;return {sendAudio:async()=>{},sendToolResponse:async()=>{},close:async()=>{}};},onToolCall:async()=>({status:'unavailable'}),onTranscript:async({transcript})=>stored.push(transcript),onSessionEnd:async()=>{}});
  const callSid='CA'+'d'.repeat(32),streamSid='MZ'+'d'.repeat(32);const started=await bridge.startMediaSession({socket,context:{ownerId:'synthetic-tail',accountSid:ACCOUNT,callSid},session:{}});socket.emit('message',JSON.stringify({event:'connected',protocol:'Call',version:'1.0.0'}),false);socket.emit('message',JSON.stringify({event:'start',sequenceNumber:'1',streamSid,start:{accountSid:ACCOUNT,callSid,streamSid,tracks:['inbound'],mediaFormat:{encoding:'audio/x-mulaw',sampleRate:8000,channels:1}}}),false);await started.controller.whenIdle();assert.ok(callbacks);
  const pending=callbacks.onTranscript({text:'[SYNTHETIC] Correct callback: use my email instead.',role:'user',final:true});socket.emit('close');await pending;await started.controller.done;
  return {meetsExpectation:stored.length===1,actual:{stored,outcome:await started.controller.done}};
 });
 await experiment('E27','Signed anonymous caller is answered with an honest contact-capture path, not rejected before tenant resolution.',async()=>{const h=await harness();try{const r=await h.post('/api/twilio/voice/incoming',{From:'anonymous'}),body=await r.text();return {meetsExpectation:r.status===200,actual:{status:r.status,body,callCount:db.prepare('SELECT COUNT(*) n FROM calls WHERE ownerId=?').get(h.owner).n}};}finally{await h.close();}});
 await experiment('E26','Buffered model transcript is flushed on local transport close for an accurate written record.',async()=>{const h=await harness();try{await h.connect();h.callbacks.onmessage({serverContent:{outputTranscription:{text:'[SYNTHETIC] I will have the owner call after 5.'}}});await delay(20);h.ws.close();await until(()=>db.prepare('SELECT status FROM calls WHERE ownerId=? AND callSid=?').get(h.owner,h.context.callSid)?.status==='COMPLETED');const row=db.prepare('SELECT transcriptJson FROM calls WHERE ownerId=? AND callSid=?').get(h.owner,h.context.callSid);return {meetsExpectation:row.transcriptJson.includes('call after 5'),actual:{storedTranscript:JSON.parse(row.transcriptJson)}};}finally{await h.close();}});

 await experiment('E42','Duplicate signed inbound events create one live session and never reopen a completed call.',async()=>{
  const h=await harness(),extras=[];try{await h.connect();const r=await h.post('/api/twilio/voice/incoming'),xml=await r.text(),url=xml.match(/<Stream url="([^"]+)"/)?.[1];if(url){const sid='MZ'+'e'.repeat(32),ws=new WebSocket('ws://127.0.0.1:'+h.ws.url.match(/:(\d+)\//)[1]+new URL(url).pathname,{headers:{'x-twilio-signature':twilio.getExpectedTwilioSignature(TOKEN,url,{})}});extras.push(ws);await once(ws,'open');ws.send(JSON.stringify({event:'connected',protocol:'Call',version:'1.0.0'}));ws.send(JSON.stringify({event:'start',sequenceNumber:'1',streamSid:sid,start:{accountSid:ACCOUNT,callSid:h.context.callSid,streamSid:sid,tracks:['inbound'],mediaFormat:{encoding:'audio/x-mulaw',sampleRate:8000,channels:1}}}));await until(()=>h.providerOpens===2);}
  const liveBeforeStop=h.providerOpens;await h.stop();const secondStillOpen=extras[0]?.readyState===WebSocket.OPEN;const repeated=await h.post('/api/twilio/voice/incoming'),afterXml=await repeated.text();
  return {meetsExpectation:liveBeforeStop===1&&!afterXml.includes('<Stream'),actual:{oneCallRow:db.prepare('SELECT COUNT(*) n FROM calls WHERE ownerId=? AND callSid=?').get(h.owner,h.context.callSid).n,providerOpens:liveBeforeStop,secondSocketOpenAfterCompleted:secondStillOpen,completedCallReceivesFreshStream:afterXml.includes('<Stream')}};
  }finally{for(const socket of extras)socket.terminate();await h.close();}
 });
 await experiment('E43','Six simultaneous calls respect the default five-session owner ceiling and save an excess-call fallback.',async()=>{
  const h=await harness(),extras=[];try{await h.connect();const responses=[];for(let i=0;i<5;i++){const callSid='CA'+(1000+i).toString(16).padStart(32,'0'),r=await h.post('/api/twilio/voice/incoming',{CallSid:callSid}),xml=await r.text(),url=xml.match(/<Stream url="([^"]+)"/)?.[1];responses.push({status:r.status,stream:!!url});if(!url)continue;const streamSid='MZ'+(1000+i).toString(16).padStart(32,'0'),socket=new WebSocket('ws://127.0.0.1:'+h.ws.url.match(/:(\d+)\//)[1]+new URL(url).pathname,{headers:{'x-twilio-signature':twilio.getExpectedTwilioSignature(TOKEN,url,{})}});extras.push(socket);await once(socket,'open');socket.send(JSON.stringify({event:'connected',protocol:'Call',version:'1.0.0'}));socket.send(JSON.stringify({event:'start',sequenceNumber:'1',streamSid,start:{accountSid:ACCOUNT,callSid,streamSid,tracks:['inbound'],mediaFormat:{encoding:'audio/x-mulaw',sampleRate:8000,channels:1}}}));await until(()=>h.providerOpens>=i+2);}
  return {meetsExpectation:h.providerOpens<=5&&responses.some(r=>!r.stream),actual:{providerOpens:h.providerOpens,additionalResponses:responses,excessCaptureLeads:db.prepare('SELECT COUNT(*) n FROM leads WHERE ownerId=?').get(h.owner).n}};
  }finally{for(const socket of extras)socket.terminate();await h.close();}
 });
 await experiment('E35','Voice callback promises use an explicit owner-policy precedence over fixed historical time promises.',async()=>{const {compileVoiceSystemInstruction}=await import('../../server/src/voice/voicePromptCompiler.js');const guideText=fs.readFileSync(new URL('../../specs/voice_quote_flows.md',import.meta.url),'utf8');const policy='[SYNTHETIC] No same-day quote or callback. Quotes and callbacks are provided on the next business day.';const prompt=compileVoiceSystemInstruction({guideText,business:{businessName:'Synthetic service company',agentName:'Synthetic assistant'},services:[],knowledge:{policies:policy}});return {meetsExpectation:!prompt.includes('have your quote today'),actual:{ownerPolicyIncluded:prompt.includes(policy),fixedSameDayPromiseIncluded:prompt.includes('have your quote today'),fixedTextMinutePromiseIncluded:prompt.includes('text confirmation in a minute'),neverInventNotificationsIncluded:prompt.includes('Never invent availability, successful notifications or a transfer.')}};});
}finally{db.close();fs.rmSync(temporary,{recursive:true,force:true});fs.writeFileSync(new URL('./phone-results.json',import.meta.url),JSON.stringify({auditedSha:'73c00622d6f2df31f57773b32e41355a7421f1a3',syntheticOnly:true,experiments:results},null,2)+'\n');}
if(results.some(result=>result.experimentError))process.exitCode=1;
