import React,{useEffect,useState} from 'react';
import {api} from './api.js';
import {AppShell,Button,Field,Select,TextInput,Textarea,Notice,ErrorMessage,PageHeader} from './ui.jsx';
import {CustomerMeasurements} from './quoteDoneControls.jsx';

export function QuoteAccess(){const [access,setAccess]=useState(null),[origins,setOrigins]=useState(''),[error,setError]=useState(null);useEffect(()=>{api('/api/quotedone/access').then(v=>{setAccess(v);setOrigins(v.allowedOrigins.join('\n'));}).catch(setError);},[]);async function save(){try{const v=await api('/api/quotedone/access',{method:'POST',body:{allowedOrigins:origins.split(/\s+/).filter(Boolean)}});setAccess(v);setError(null);}catch(e){setError(e);}}return <section className="editor-section"><h2>Customer quote link</h2><Field label="Allowed website origins" help="Enter the exact HTTPS website origins. Local HTTP origins are available only for non-production verification."><Textarea value={origins} onChange={e=>setOrigins(e.target.value)}/></Field><Button variant="secondary" onClick={()=>setOrigins(window.location.origin)}>Use this website origin</Button><Button onClick={save}>Save quote-link access</Button>{access?.publicKey&&<p><a href={'/quote/'+access.publicKey} target="_blank" rel="noreferrer">Open customer quote form</a></p>}<ErrorMessage error={error}/></section>;}
export function CustomerQuote({publicKey}){
 const [services,setServices]=useState([]),[serviceId,setServiceId]=useState(''),[inputs,setInputs]=useState({}),[contact,setContact]=useState({}),[location,setLocation]=useState(''),[context,setContext]=useState(''),[unknowns,setUnknowns]=useState(''),[urgency,setUrgency]=useState(''),[fees,setFees]=useState({}),[result,setResult]=useState(null),[pending,setPending]=useState(null),[sending,setSending]=useState(false),[error,setError]=useState(null);
 const cacheKey='quotedone-pending-'+publicKey;
 useEffect(()=>{api('/api/public/quote/'+publicKey,{auth:false}).then(v=>setServices(v.services)).catch(setError);try{const prior=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(prior)setPending(prior);}catch{}},[publicKey]);
 const service=services.find(s=>s.id===serviceId);
 async function send(){setSending(true);setError(null);try{const submission=pending||{requestId:crypto.randomUUID(),serviceId,serviceRequest:service?.name,customerInputs:inputs,contact,location,context,explicitUnknowns:unknowns,urgency,customerFeeSelections:fees};setPending(submission);sessionStorage.setItem(cacheKey,JSON.stringify(submission));const response=await api('/api/public/quote/'+publicKey,{method:'POST',body:submission,auth:false});setResult(response);setPending(null);sessionStorage.removeItem(cacheKey);}catch(e){setError(e);}finally{setSending(false);}}
 return <main className="pricebook-page"><PageHeader eyebrow="QUOTEDONE" title="Request an estimate" description="Share your project details. When measurements or pricing need verification, the business will review your saved request."/>{result?<><QuoteResult result={result}/><Button variant="secondary" onClick={()=>{setResult(null);setInputs({});setServiceId('');}}>Start another request</Button></>:<>
 {pending?<Notice title="Submission awaiting confirmation">Retry sends the exact same request. It will not create another quote or lead if the first save succeeded.</Notice>:<><Field label="Service"><Select aria-label="Service" value={serviceId} onChange={e=>{setServiceId(e.target.value);setInputs({});setFees({});}}><option value="">Choose a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field>{service&&<CustomerMeasurements fields={service.customerFields} value={inputs} onChange={setInputs} knownOfferings={service.knownOfferings}/>}<section className="editor-section"><h2>Contact and project details</h2>{['name','email','phone'].map(field=><Field key={field} label={field[0].toUpperCase()+field.slice(1)}><TextInput value={contact[field]||''} onChange={e=>setContact({...contact,[field]:e.target.value})}/></Field>)}<Field label="Project location"><TextInput value={location} onChange={e=>setLocation(e.target.value)}/></Field><Field label="Measurements or facts you do not know"><Textarea value={unknowns} onChange={e=>setUnknowns(e.target.value)}/></Field><Field label="Urgency"><TextInput value={urgency} onChange={e=>setUrgency(e.target.value)}/></Field><Field label="Additional project details"><Textarea value={context} onChange={e=>setContext(e.target.value)}/></Field>{service?.customerFees?.map(fee=><Field key={fee} label={'Select '+fee+' charge'}><Select aria-label={'Select '+fee+' charge'} value={fees[fee]===undefined?'':String(fees[fee])} onChange={e=>setFees({...fees,[fee]:e.target.value===''?undefined:e.target.value==='true'})}><option value="">Unknown / not supplied</option><option value="true">Yes</option><option value="false">No</option></Select></Field>)}</section></>}
 <Button onClick={send} disabled={sending||(!pending&&!serviceId)}>{sending?'Saving request':pending?'Retry saved request':'Submit estimate request'}</Button></>}<ErrorMessage error={error}/></main>;
}
export function QuoteResult({result}){if(!result)return null;if(result.resultType==='ESTIMATE_REQUIRES_REVIEW')return <Notice title="Request saved for review">{result.customerMessage}</Notice>;return <section className="editor-section"><h2>Estimate</h2>{(result.options?.length?result.options:[result]).map((o,index)=><article key={index}>{o.tierName&&<h3>{o.tierName}</h3>}<strong>{o.lowEstimate===o.highEstimate?'$'+o.lowEstimate:'$'+o.lowEstimate+' – $'+o.highEstimate}</strong><ul>{(o.priceDrivers||[]).map((driver,i)=><li key={i}>{driver}</li>)}</ul><p>{o.disclaimer||result.disclaimer}</p></article>)}</section>;}
export function QuoteRecords({kind}) {
 const [rows,setRows]=useState([]),[error,setError]=useState(null);
 const load=()=>api('/api/'+kind).then(v=>{setRows(v[kind]);setError(null);}).catch(setError);
 useEffect(()=>{load();},[kind]);
 async function status(id,next){try{await api('/api/leads/'+id,{method:'PATCH',body:{status:next}});await load();}catch(e){setError(e);}}
 return <AppShell activePath={'/'+kind}><main className="pricebook-page"><PageHeader eyebrow="QUOTEDONE" title={kind==='leads'?'Leads':'Quotes'}/><Button variant="secondary" onClick={load}>Refresh</Button>{!rows.length&&<Notice>No saved {kind} yet.</Notice>}{rows.map(row=><section className="editor-section" key={row.id}><h2>{row.describedService||row.serviceType}</h2><p>{row.status} · {row.createdAt}</p>{kind==='leads'?<><dl><dt>Customer</dt><dd>{row.customerName||'Not supplied'}</dd><dt>Phone</dt><dd>{row.callerNumber||'Not supplied'}</dd></dl><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify({contact:row.contact,location:row.location,measurementsAndScope:row.customerInputs,unknowns:row.explicitUnknowns,urgency:row.urgency,context:row.context},null,2)}</pre><Button onClick={()=>status(row.id,row.status==='DISMISSED'?'NEEDS REVIEW':'DISMISSED')}>{row.status==='DISMISSED'?'Reopen for review':'Dismiss'}</Button></>:<QuoteResult result={row.result}/>} {row.internal&&<details><summary>Owner-only calculation and request evidence</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(row.internal,null,2)}</pre></details>}</section>)}<ErrorMessage error={error}/></main></AppShell>;
}
