import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {once} from 'node:events';
import {mkdirSync,mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,createHash} from 'node:crypto';
// Read-only revision observation, identical to bridge canonical/digest. Do not
// import the bridge here: its database must initialize only after the synthetic
// voice fixture selects DATABASE_PATH below.
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])])):value;
const bookRevision=value=>createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
import {encryptCredentialPayload} from '../../server/src/credentialEncryption.js';

const here=dirname(fileURLToPath(import.meta.url)),repo=resolve(here,'../..'),raw=join(process.env.REHEARSAL_OUTPUT||here,'raw'),shots=join(process.env.REHEARSAL_OUTPUT||here,'screenshots');
mkdirSync(raw,{recursive:true});mkdirSync(shots,{recursive:true});mkdirSync(join(repo,'.tmp'),{recursive:true});
const volume=mkdtempSync(join(repo,'.tmp','first-customer-'));
const stateFile=join(volume,'synthetic-provider.json'),mailFile=join(volume,'synthetic-mail.json');
writeFileSync(stateFile,JSON.stringify({syntheticOnly:true,now:new Date().toISOString(),mode:'normal',calls:[],events:{}}));writeFileSync(mailFile,'[]');
const evidence={sourceCommit:process.env.REHEARSAL_COMMIT||null,base:'be473b6542c498a6e96b056b5be2c3d59d9e4055',runtime:{node:process.version,volume,fakes:['test/fixtures/bookingCalendarProvider20261006.mjs','test/accountEmail.spec.mjs fake Resend delivery shape']},steps:[],requests:[],console:[],server:[]};
function writeEvidence(){
  // Raw observations are reproducible, but issued synthetic bearer/verification
  // credentials should not be carried into a Git commit.
  const redacted=JSON.stringify(evidence,null,2)
    .replace(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g,'[SYNTHETIC_JWT_REDACTED]')
    .replace(/(verify-email#token=)[A-Za-z0-9_-]+/g,'$1[SYNTHETIC_TOKEN_REDACTED]');
  writeFileSync(join(raw,'execution.json'),redacted);
}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const value=server.address().port;await new Promise(r=>server.close(r));return value;}
const serverPort=await port(),base='http://127.0.0.1:'+serverPort,publicUrl='https://synthetic-app.example.invalid',widgetUrl='https://synthetic-widget.example.invalid';
const env={...process.env,NODE_ENV:'production',PORT:String(serverPort),TRUST_PROXY:'none',RAILWAY_VOLUME_MOUNT_PATH:volume,RAILWAY_DEPLOYMENT_DRAINING_SECONDS:'120',APP_DATA_DIR:volume,DATABASE_PATH:join(volume,'off-the-clock.sqlite'),PRICEBOOK_PATH:join(volume,'pricebooks'),RAILWAY_ENVIRONMENT_ID:'',LOCAL_PREVIEW_MODE:'false',LOCAL_PREVIEW:'false',JWT_SECRET:'SYNTHETIC_REHEARSAL_JWT_'+randomBytes(40).toString('hex'),CREDENTIAL_ENCRYPTION_KEY:randomBytes(32).toString('hex'),BOOKING_SLOT_TOKEN_SECRET:'SYNTHETIC_BOOKING_'+randomBytes(40).toString('hex'),PUBLIC_BASE_URL:publicUrl,CLIENT_URL:publicUrl,CORS_ALLOWED_ORIGINS:publicUrl+','+widgetUrl,BOOKING_SYNTHETIC_PROVIDER:stateFile,FIRST_CUSTOMER_MAIL_LOG:mailFile,EMAIL_PROVIDER:'console',EMAIL_DELIVERY_ENABLED:'false',ALLOW_PROVIDER_WRITES:'true',VOICE_RUNTIME_ENABLED:'false',STRIPE_BILLING_ENABLED:'false',OUTBOUND_WEBHOOKS_ENABLED:'false',DEMO_ENABLED:'false',GOOGLE_CLIENT_ID:'SYNTHETIC_CLIENT',GOOGLE_CLIENT_SECRET:'SYNTHETIC_SECRET',GOOGLE_CALENDAR_REDIRECT_URI:publicUrl+'/api/onboarding/calendar/google/callback',TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_API_KEY_SID:'SK'+'a'.repeat(32),TWILIO_API_KEY_SECRET:'SYNTHETIC_NEVER_LIVE',GEMINI_API_KEY:'SYNTHETIC_NEVER_LIVE',GEMINI_MODEL:'synthetic-live-model'};
delete env.GEMINI_TEXT_MODEL;
let child;
async function boot(provider='console'){
 env.EMAIL_PROVIDER=provider;env.EMAIL_DELIVERY_ENABLED=provider==='resend'?'true':'false';env.RESEND_API_KEY=provider==='resend'?'re_SYNTHETIC_NEVER_LIVE':'';env.EMAIL_FROM='synthetic-sender@example.invalid';
 child=spawn(process.execPath,['--import','./verification/first-customer-20261009/fakeProviders.mjs','server/src/server.js'],{cwd:repo,env,stdio:['ignore','pipe','pipe']});
 for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>{evidence.server.push(chunk.toString());writeFileSync(join(raw,'server.log'),evidence.server.join(''));});
 const deadline=Date.now()+30000;while(!evidence.server.join('').includes('Off The Clock AI server listening')){if(child.exitCode!==null)throw Error('Server exited: '+evidence.server.join(''));if(Date.now()>deadline)throw Error('Server startup timeout: '+evidence.server.join(''));await sleep(50);}
}
async function stop(){if(child?.exitCode===null){child.kill('SIGTERM');await Promise.race([once(child,'exit'),sleep(5000)]);if(child.exitCode===null)child.kill('SIGKILL');}}
const require=createRequire(import.meta.url),{chromium}=require(process.env.PRICEBOOK_BROWSER_MODULE||'playwright');
const Database=require('better-sqlite3');
async function seedTrial(email){const db=new Database(join(volume,'off-the-clock.sqlite'));try{const account=db.prepare('SELECT id,plan FROM users WHERE email=?').get(email);if(!account)throw Error('Synthetic account missing: '+email);const at=new Date().toISOString(),starts=Math.floor(Date.now()/1000)-120,endsSeconds=starts+14*86400,ends=new Date(endsSeconds*1000).toISOString(),customer='cus_SYNTHETIC_'+account.plan,subscription='sub_SYNTHETIC_'+account.plan;db.prepare('INSERT INTO billingAccounts(ownerId,stripeCustomerId,stripeSubscriptionId,paymentMethodVerifiedAt,createdAt,updatedAt) VALUES(?,?,?,?,?,?)').run(account.id,customer,subscription,at,at,at);db.prepare('INSERT INTO billingSubscriptionEvidence(stripeSubscriptionId,ownerId,stripeCustomerId,eventCreatedAt,stateJson,ambiguous) VALUES(?,?,?,?,?,0)').run(subscription,account.id,customer,starts,JSON.stringify({trialStart:starts,trialEnd:endsSeconds,status:'trialing',plan:account.plan,billingInterval:'monthly'}));db.prepare("UPDATE users SET planStatus='trialing',trialEndsAt=? WHERE id=? AND ownerId IS NULL").run(ends,account.id);evidence.runtime.syntheticBillingSeed=(evidence.runtime.syntheticBillingSeed||[]).concat({email,ownerId:account.id,plan:account.plan,trialEndsAt:ends,source:'test/fixtures/bookingCalendarApplication20261006.mjs payment evidence plus billingVoiceUsage.js trialStart/trialEnd shape'});return account.id;}finally{db.close();}}
let browser,page,context;
const snap=async name=>{const path=join(shots,name+'.png');await page.screenshot({path,fullPage:true});return path;};
async function step(number,name,run){const entry={number,name,status:'blocked',expected:'See EXPECTED.md',startedAt:new Date().toISOString()};evidence.steps.push(entry);try{entry.actual=await run();entry.status='pass';}catch(error){entry.status='fail';entry.error=String(error.stack||error.message||error);entry.actual=await page.locator('body').innerText().catch(()=>'(browser unavailable)');}finally{entry.screenshot=await snap('step-'+number).catch(error=>'Screenshot error: '+error.message);writeEvidence();}return entry;}
async function login(email,password){await page.goto(publicUrl+'/onboarding?mode=login');await page.getByRole('button',{name:'Sign in',exact:true}).first().click();await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).last().click();await page.waitForTimeout(300);}
try{
 await boot();browser=await chromium.launch({headless:true,...(process.env.PRICEBOOK_BROWSER_EXECUTABLE?{executablePath:process.env.PRICEBOOK_BROWSER_EXECUTABLE}:{})});context=await browser.newContext({viewport:{width:1440,height:1000}});
 const proxyApplication=async route=>{const req=route.request(),url=new URL(req.url()),headers={...req.headers(),host:'127.0.0.1:'+serverPort};delete headers['content-length'];const response=await fetch(base+url.pathname+url.search,{method:req.method(),headers,body:['GET','HEAD'].includes(req.method())?undefined:req.postDataBuffer(),redirect:'manual'});const outgoing=Object.fromEntries(response.headers);delete outgoing['content-length'];delete outgoing['content-encoding'];delete outgoing['transfer-encoding'];await route.fulfill({status:response.status,headers:outgoing,body:Buffer.from(await response.arrayBuffer())});};
 await context.route(publicUrl+'/**',proxyApplication);
 page=await context.newPage();
 page.on('console',m=>{if(m.type()==='error')evidence.console.push({type:'console',text:m.text(),url:page.url()});});page.on('pageerror',e=>evidence.console.push({type:'pageerror',text:e.stack||e.message,url:page.url()}));
 page.on('request',request=>{if(!request.url().includes('/api/pricebook/'))return;let body;try{body=request.postDataJSON();}catch{}evidence.requests.push({event:'request',at:new Date().toISOString(),method:request.method(),url:request.url(),submittedRevision:body?.revision});});
 page.on('response',async response=>{if(!response.url().includes('/api/'))return;let body,parsed,submitted;try{body=await response.text();parsed=JSON.parse(body);}catch{}try{submitted=response.request().postDataJSON();}catch{}
  evidence.requests.push({event:'response',at:new Date().toISOString(),method:response.request().method(),url:response.url(),status:response.status(),submittedRevision:submitted?.revision,returnedRevision:parsed?.revision||parsed?.bookRevision,body:body?.slice(0,4000)});
 });
 async function inspectPricebook(name){
  await page.waitForTimeout(700);
  const text=await page.locator('main').innerText();
  const keys=[...new Set(text.replace(/https?:\/\/\S+|\S+@\S+|\bQuoteDone\b/g,'').match(/\b[A-Za-z]\w*(?:\.[A-Za-z_]\w*)+\b|\b[a-z]+[A-Z][A-Za-z0-9]*\b/g)||[])];
  const owner=evidence.runtime.syntheticBillingSeed?.[1]?.ownerId;
  let diskRevision;try{diskRevision=bookRevision(JSON.parse(readFileSync(join(volume,'pricebooks',owner+'.json'),'utf8')));}catch{}
  const observation={name,rawKeys:keys,recoveryDialogs:await page.getByRole('dialog').count(),diskRevision,text,screenshot:await snap(name)};
  (evidence.pricebookScreens||=[]).push(observation);writeEvidence();
  return observation;
 }
 await step(1,'Signup and console verification',async()=>{
  await page.goto(publicUrl+'/signup?plan=Operator');await page.getByLabel('Owner first name').fill('Synthetic Ophelia');await page.getByLabel('Business name').fill('[SYNTHETIC] Operator Works');await page.getByLabel('Email').fill('operator@example.invalid');await page.getByLabel('Password').fill('SYNTHETIC-Test-Pass-123!');await page.getByRole('button',{name:'Operator',exact:true}).click();await page.getByRole('button',{name:'Start setup'}).click();await page.getByText('Check your email to verify your account').waitFor();
  const consoleOutput=evidence.server.join('');if(!consoleOutput.includes('[email:console]'))throw Error('No console delivery marker after signup');
  const link=consoleOutput.match(/https?:\/\/[^\s]+\/verify-email#token=[^\s]+/);if(!link)throw Error('Console delivery logged only a simulated marker, not a verification link; browser says “Check your email”.');
  await page.goto(link[0]);
  return 'Operator verified via console link';
 });
 // The console mode intentionally keeps tokens out of logs. Continue with the
 // exact fake transactional-email shape used by accountEmail.spec.mjs.
 await stop();evidence.server=[];writeFileSync(stateFile,JSON.stringify({...JSON.parse(readFileSync(stateFile,'utf8')),now:new Date(Date.now()+61000).toISOString()}));await boot('resend');
 await step('1b','Complete both accounts with fake email delivery and session lifecycle',async()=>{
  await page.goto(publicUrl+'/resend-verification');await page.getByLabel('Email').fill('operator@example.invalid');await page.getByRole('button',{name:'Request email'}).click();await page.getByText(/Request received/).waitFor();
  let messages=JSON.parse(readFileSync(mailFile,'utf8'));if(!messages.length)throw Error('Fake email did not capture verification link');
  await page.goto(messages.at(-1).text.match(/https?:\/\/[^\s]+/)[0]);await page.getByRole('button',{name:'Verify email'}).click();await page.getByText('Your email is verified.').waitFor();
  await login('operator@example.invalid','SYNTHETIC-Test-Pass-123!');await page.getByRole('button',{name:'Sign out'}).waitFor();
  await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('heading',{name:'Put your operator on the line.'}).waitFor();
  await login('operator@example.invalid','SYNTHETIC-Test-Pass-123!');await page.getByRole('button',{name:'Sign out'}).waitFor();
  await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('heading',{name:'Put your operator on the line.'}).waitFor();
  await page.goto(publicUrl+'/signup?plan=QuoteDone');await page.getByLabel('Owner first name').fill('Synthetic Quinn');await page.getByLabel('Business name').fill('[SYNTHETIC] Quinn Trades');await page.getByLabel('Email').fill('quotedone@example.invalid');await page.getByLabel('Password').fill('SYNTHETIC-Test-Pass-123!');await page.getByRole('button',{name:'QuoteDone',exact:true}).click();await page.getByRole('button',{name:'Start setup'}).click();await page.getByText('Check your email to verify your account').waitFor();
  messages=JSON.parse(readFileSync(mailFile,'utf8'));if(messages.length!==2)throw Error('Expected two fake email deliveries; got '+messages.length);
  await page.goto(messages.at(-1).text.match(/https?:\/\/[^\s]+/)[0]);await page.getByRole('button',{name:'Verify email'}).click();await page.getByText('Your email is verified.').waitFor();
  await login('quotedone@example.invalid','SYNTHETIC-Test-Pass-123!');await page.getByRole('button',{name:'Sign out'}).waitFor();
  await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('heading',{name:'Put your operator on the line.'}).waitFor();await login('quotedone@example.invalid','SYNTHETIC-Test-Pass-123!');await page.getByRole('button',{name:'Sign out'}).waitFor();
  return {operatorAndQuoteDoneVerified:true,logoutAndRelogin:true,mailCount:messages.length,accountPage:(await page.locator('main').innerText()).slice(0,650)};
 });
 await step('trial-fixture','Simulate verified trial payment evidence with existing synthetic pattern',async()=>({operator:await seedTrial('operator@example.invalid'),quoteDone:await seedTrial('quotedone@example.invalid')}));
 await step(2,'Missing text AI and manual business knowledge',async()=>{
  await page.goto(publicUrl+'/onboarding?step=2');await page.getByRole('heading',{name:'What work do you do?'}).waitFor();
  for(const trade of ['Painting','Fencing','Landscaping'])await page.getByRole('button',{name:trade,exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Set your jurisdiction'}).waitFor();
  await page.getByLabel('State code').fill('ME');await page.getByLabel("I pay sales tax when I buy materials and don't add a tax line to customer invoices.").check();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Plug in your line'}).waitFor();
  await page.goto(publicUrl+'/onboarding?step=5');await page.getByRole('heading',{name:'Load your business knowledge'}).waitFor();
  await page.getByRole('button',{name:'Draft from my business'}).click();await page.getByText(/text model is not configured/i).waitFor();await snap('step-2-ai-unavailable');
  const response=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/onboarding/knowledge-base/draft');if(response?.status!==503||!response.body.includes('TEXT_AI_UNAVAILABLE'))throw Error('Expected 503 TEXT_AI_UNAVAILABLE; got '+JSON.stringify(response));
  await page.getByLabel('About & area').fill('[SYNTHETIC] Quinn Trades serves Halifax.');await page.getByLabel('Hours',{exact:true}).fill('Monday to Friday, 9 am to 5 pm.');await page.getByLabel('Services',{exact:true}).fill('Fence installation, lawn mowing and interior painting.');await page.getByLabel('Your prices').fill('Consultation: $20.');await page.getByRole('button',{name:'Review and save'}).click();await page.getByRole('heading',{name:'Put your operator on the line'}).waitFor();
  await page.goto(publicUrl+'/onboarding?step=5');await page.getByRole('heading',{name:'Load your business knowledge'}).waitFor();const about=await page.getByLabel('About & area').inputValue();if(about!=='[SYNTHETIC] Quinn Trades serves Halifax.')throw Error('Manual About did not persist: '+about);
  return {aiResponse:response,manualAbout:about};
 });
 await step(3,'Owner configures and reloads three service rates',async()=>{
  await page.goto(publicUrl+'/pricebook');await page.getByRole('heading',{name:'Price book',exact:true}).waitFor();
  await inspectPricebook('pricebook-new-owner');
  const choose=async name=>{await page.locator('.service-pick').filter({hasText:name}).first().click();await page.getByRole('heading',{name,exact:true}).last().waitFor();};
  const rate=async(key,value)=>await page.locator('#field-'+key+' input').first().fill(String(value));
  await choose('Fencing installation');await page.getByLabel('Offering pricing').selectOption('installed');await page.getByLabel('Included job description').fill('Six-foot treated fence, standard posts and footings, flat ground');await page.getByLabel('New fence type name').fill('Treated wood');await page.getByRole('button',{name:'Use this fence type'}).click();await page.getByLabel('Height these prices are for whole feet').fill('6');await page.getByLabel('Standard posts, footings and digging included').fill('Standard posts and footings included');await page.getByRole('button',{name:'No gates offered'}).click();
  const fenceInputs=await page.locator('section.editor-section').filter({has:page.getByRole('heading',{name:'Fence and painting offering'})}).first().locator('input[aria-label]').evaluateAll(nodes=>nodes.map(n=>({label:n.getAttribute('aria-label'),value:n.value})));
  const installed=fenceInputs.find(x=>/installed.*(foot|lf)/i.test(x.label||''));if(!installed)throw Error('Fence installed price field not found: '+JSON.stringify(fenceInputs));await page.getByLabel(installed.label,{exact:true}).fill('25.98');await rate('minimumJob','0');await page.getByRole('switch',{name:'Enable quoting for this service'}).click();
  await choose('Mowing');await rate('mowingBaseRatePerSqft','0.10');await rate('minimumServiceCharge','0');for(const label of ['Weekly price','Biweekly price','Monthly price','One time price','Maintained price','Overgrown price','Severe price']){const input=page.getByLabel(label,{exact:true});if(await input.count())await input.fill('1');}await page.getByRole('switch',{name:'Enable quoting for this service'}).click();
  await choose('Interior painting');await rate('laborPerWallSqftPerCoat','2');await rate('materialPerWallSqftPerCoat','1');await rate('minimumJob','0');await page.getByRole('switch',{name:'Enable quoting for this service'}).click();await page.getByText('Quantity assumptions',{exact:true}).click();await page.getByLabel('Finish paint material waste').fill('0');
  await page.getByText('Markup and margin',{exact:true}).click();await page.getByLabel('Markup (%)').fill('0');await page.getByRole('button',{name:'Save & validate'}).click();await page.waitForTimeout(700);
  const save=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/pricebook/save');if(save?.status!==200)throw Error('Price book save failed: '+JSON.stringify(save)+'; screen '+(await page.locator('main').innerText()).slice(-2800));
  await page.reload();await choose('Mowing');const mow=await page.locator('#field-mowingBaseRatePerSqft input').inputValue();await choose('Interior painting');const paint=await page.locator('#field-laborPerWallSqftPerCoat input').inputValue();await choose('Fencing installation');const fence=await page.getByLabel(installed.label,{exact:true}).inputValue();if(mow!=='0.1'||paint!=='2'||fence!=='25.98')throw Error('Rates changed across reload: '+JSON.stringify({mow,paint,fence}));
  await inspectPricebook('pricebook-three-services');
  const persisted=JSON.parse(readFileSync(join(volume,'pricebooks',evidence.runtime.syntheticBillingSeed[1].ownerId+'.json'),'utf8'));const serviceStatuses=persisted.services.filter(s=>['FENCING_INSTALL','LANDSCAPING_MOWING','INTERIOR_PAINTING'].includes(s.serviceType)).map(s=>({type:s.serviceType,active:s.active,rate:s.pricing?.offeringRates?.installedFencePerLF??s.pricing?.mowingBaseRatePerSqft??s.pricing?.laborPerWallSqftPerCoat}));
  return {fenceInputs,saveStatus:save.status,reloadedRates:{mow,paint,fence},serviceStatuses,screen:(await page.locator('main').innerText()).slice(-1700)};
 });
 await step(4,'Calendar availability save and reload',async()=>{
  await page.goto(publicUrl+'/calendar');await page.getByRole('heading',{name:'Calendar',exact:true}).waitFor();await page.getByRole('tab',{name:'Availability'}).click();const form=page.getByRole('form',{name:'Booking availability'});await form.getByLabel('Timezone').selectOption('America/Halifax');
  for(const day of ['Monday','Tuesday','Wednesday','Thursday','Friday']){await form.getByRole('button',{name:'Add '+day+' hours'}).click();await form.getByLabel(day+' start 1').fill('09:00');await form.getByLabel(day+' end 1').fill('17:00');}
  for(const [label,value] of [['Days ahead customers can book','14'],['Minimum notice (minutes)','120'],['Start time intervals (minutes)','60'],['Buffer before appointments (minutes)','15'],['Buffer after appointments (minutes)','15']])await form.getByLabel(label).fill(value);
  await form.getByLabel('Allow customers to book available times').check();await form.getByRole('button',{name:'Add blocked period'}).click();await form.getByLabel('Blocked period 1 start').fill('2026-10-12T10:00');await form.getByLabel('Blocked period 1 end').fill('2026-10-12T11:00');await form.getByRole('button',{name:'Save availability'}).click();await page.getByText('Availability saved.').waitFor();
  await page.reload();await page.getByRole('tab',{name:'Availability'}).click();const reloaded=page.getByRole('form',{name:'Booking availability'});const actual={timezone:await reloaded.getByLabel('Timezone').inputValue(),minNotice:await reloaded.getByLabel('Minimum notice (minutes)').inputValue(),horizon:await reloaded.getByLabel('Days ahead customers can book').inputValue(),before:await reloaded.getByLabel('Buffer before appointments (minutes)').inputValue(),after:await reloaded.getByLabel('Buffer after appointments (minutes)').inputValue(),block:await reloaded.getByLabel('Blocked period 1 start').inputValue(),direct:await reloaded.getByLabel('Allow customers to book available times').isChecked()};if(JSON.stringify(actual)!==JSON.stringify({timezone:'America/Halifax',minNotice:'120',horizon:'14',before:'15',after:'15',block:'2026-10-12T10:00',direct:true}))throw Error('Calendar changed after reload: '+JSON.stringify(actual));return actual;
 });
 await step('3b','Complete owner quote rules and saved approval',async()=>{
  await page.goto(publicUrl+'/pricebook');await page.getByRole('heading',{name:'Price book',exact:true}).waitFor();
  const categories=['labor','material','removal','prep','addon','equipment','travel','disposal','permit','overhead','surcharge'],names=['Fencing installation','Mowing','Interior painting'];
  for(const name of names){await page.locator('.service-pick').filter({hasText:name}).first().click();await page.getByText('Quote configuration',{exact:true}).last().click();for(const category of categories){await page.getByLabel(category+' price basis').selectOption(category==='material'?'sell_price':'cost');await page.getByLabel(category+' taxability').selectOption('false');await page.getByLabel(category+' markup applies').selectOption('false');}for(const fee of ['travel','disposal','permit','overhead'])await page.getByLabel(fee+' fee rule').selectOption('not_applicable');}
  for(const field of ['Overhead fixed ($)','Minimum job price ($)','Travel fee ($)','Disposal fee ($)','Permit fee ($)'])await page.getByLabel(field,{exact:true}).fill('0');await page.getByLabel('Estimate range buffer (%)').fill('0');
  await page.getByRole('button',{name:'Save & validate'}).click();await page.waitForTimeout(500);const save=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/pricebook/save');if(save?.status!==200)throw Error('Rules save '+JSON.stringify(save));
  const approvals=[];for(const name of names){await page.reload();await page.locator('.service-pick').filter({hasText:name}).first().click();await page.getByRole('button',{name:'Review saved configuration'}).click();await page.getByRole('table',{name:'Saved prices and configuration'}).waitFor();const review=(await page.getByRole('table',{name:'Saved prices and configuration'}).innerText()).slice(0,1800);await page.getByText(/I confirm these exact saved prices, units, factors and rules/).locator('input').check();if(await page.getByText(/I confirm these retained legacy settings/).count())await page.getByText(/I confirm these retained legacy settings/).locator('input').check();await page.getByRole('button',{name:'Confirm saved configuration'}).click();await page.waitForTimeout(250);approvals.push({name,review,response:evidence.requests.findLast(r=>/\/approve$/.test(new URL(r.url).pathname))});}
  await page.reload();const catalog=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/pricebook/'+evidence.runtime.syntheticBillingSeed[1].ownerId);return {saveStatus:save.status,approvals:approvals.map(a=>({name:a.name,status:a.response?.status,body:a.response?.body?.slice(0,600),review:a.review.slice(0,350)})),catalogStatus:catalog?.status,screen:(await page.locator('main').innerText()).slice(0,2400)};
 });
 await step('pricebook-review','Price Book presentation after owner approval',async()=>{const screen=await inspectPricebook('pricebook-three-approved');if(screen.rawKeys.length||screen.recoveryDialogs)throw Error(JSON.stringify({rawKeys:screen.rawKeys,recoveryDialogs:screen.recoveryDialogs}));return screen;});
 await step('4b','Booking policies and synthetic Google/calendar service-area fixture',async()=>{
  await page.goto(publicUrl+'/calendar');await page.getByRole('tab',{name:'Availability'}).click();const before=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/booking/configuration');
  const policies=[];for(const name of ['Fencing installation','Mowing','Interior painting']){const form=page.getByRole('form',{name:name+' booking settings'});await form.getByLabel(name+' booking type').selectOption('site_visit_first');await form.getByLabel(name+' duration (minutes)').fill('60');await form.getByLabel('Offer booking for '+name).check();await form.getByRole('button',{name:'Save '+name+' booking'}).click();await page.getByText(name+' booking settings saved.').waitFor();policies.push({name,response:evidence.requests.findLast(r=>r.method==='PUT'&&new URL(r.url).pathname.startsWith('/api/booking/policies/'))?.status});}
  const db=new Database(join(volume,'off-the-clock.sqlite'));const ownerId=evidence.runtime.syntheticBillingSeed[1].ownerId;try{
   const row=db.prepare('SELECT knowledgeBaseJson FROM businessProfiles WHERE ownerId=?').get(ownerId),knowledge=JSON.parse(row.knowledgeBaseJson);knowledge.serviceArea={mode:'cities',cities:[{city:'Halifax',region:'NS',country:'CA'}]};db.prepare('UPDATE businessProfiles SET knowledgeBaseJson=? WHERE ownerId=?').run(JSON.stringify(knowledge),ownerId);
   const encrypted=encryptCredentialPayload({accessToken:'SYNTHETIC-synthetic-a',refreshToken:null,tokenType:'Bearer'},{key:env.CREDENTIAL_ENCRYPTION_KEY});db.prepare("INSERT INTO calendarConnections(ownerId,provider,status,calendarId,credentialsCiphertext,credentialsIv,credentialsTag,keyVersion,scopesJson,createdAt,updatedAt) VALUES(?,'google','connected','primary',?,?,?,?,?,?,?)").run(ownerId,encrypted.credentialsCiphertext,encrypted.credentialsIv,encrypted.credentialsTag,encrypted.keyVersion,JSON.stringify(['https://www.googleapis.com/auth/calendar']),new Date().toISOString(),new Date().toISOString());db.prepare("UPDATE bookingSettings SET provider='google',calendarId='primary' WHERE ownerId=?").run(ownerId);
  }finally{db.close();}
  const provider=JSON.parse(readFileSync(stateFile,'utf8'));provider.events['synthetic-a:SYNTHETIC_BUSY']={owner:'synthetic-a',status:'confirmed',start:{dateTime:'2026-10-13T13:00:00.000Z'},end:{dateTime:'2026-10-13T14:00:00.000Z'}};writeFileSync(stateFile,JSON.stringify(provider));
  await page.reload();await page.getByRole('tab',{name:'Availability'}).click();const after=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/booking/configuration');return {policies,before:before?.body?.slice(0,1200),after:after?.body?.slice(0,1200),fixture:'test/fixtures/bookingCalendarApplication20261006.mjs encrypted Google connection; serviceAreaFromKnowledgeBase synthetic Halifax city',screen:(await page.locator('main').innerText()).slice(-2100)};
 });
 let ownerPage=page,widgetKey,widgetCatalog;
 await step('5-preflight','Allowed origin, production embed, live customer catalog',async()=>{
  await page.goto(publicUrl+'/pricebook');await page.getByRole('heading',{name:'Price book',exact:true}).waitFor();await page.getByLabel('Allowed website origins').fill(widgetUrl);await page.getByRole('button',{name:'Save quote-link access'}).click();await page.getByRole('heading',{name:'Install your website widget'}).waitFor();widgetKey=(await page.getByLabel('Widget code').inputValue()).match(/data-key="([^"]+)/)?.[1];if(!widgetKey)throw Error('No public widget key in embed code');
  await context.route(widgetUrl+'/**',async route=>route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>[SYNTHETIC] Customer website</title><h1>[SYNTHETIC] Customer website</h1><script src="'+publicUrl+'/widget.js" data-key="'+widgetKey+'"></script>'}));
  ownerPage=page;page=await context.newPage();await page.goto(widgetUrl+'/');const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/public/quote/'+widgetKey);await page.getByRole('button',{name:'Get an estimate'}).click();widgetCatalog=await (await response).json();await page.getByLabel('Service',{exact:true}).waitFor();const visible=widgetCatalog.services.map(s=>({id:s.id,name:s.name,type:s.serviceType,fields:s.customerFields}));if(visible.length<3)throw Error('Only '+visible.length+' customer services after owner approval: '+JSON.stringify(visible));return {widgetKey,host:widgetUrl,visible};
 });
 const quoteCases=[
  {label:'Fence',type:'FENCING_INSTALL',expected:2598,inputs:{linearFeet:'100',lfMethod:'exact',fenceType:'Treated wood',fenceHeight:'6',terrainSlope:'flat',gates:{},cornerCount:'0'}},
  {label:'Mowing',type:'LANDSCAPING_MOWING',expected:100,inputs:{yardSqft:'1000',sqftMethod:'exact',serviceFrequency:'one_time',grassCondition:'maintained',bagClippings:'false',edgingIncluded:'false'}},
  {label:'Interior painting',type:'INTERIOR_PAINTING',expected:600,inputs:{areaInputMethod:'wall_sqft',wallAreaSqft:'100',wallHeight:'standard',wallScopeUniform:'true',coats:'2',surfaceCondition:'good',ceilingsIncluded:'false',trimIncluded:'false'}}
 ];
 for(const item of quoteCases)await step('5-'+item.type.toLowerCase(),'Customer widget estimate: '+item.label,async()=>{
  if(!widgetKey)throw Error('No widget key; origin/embed setup did not complete');
  const service=widgetCatalog?.services?.find(s=>s.serviceType===item.type);if(!service)throw Error(item.type+' absent from public customer catalog; cannot get the expected $'+item.expected.toFixed(2)+' quote');
  page=await context.newPage();page.on('response',async r=>{if(!r.url().includes('/api/'))return;let body;try{body=await r.text();}catch{}evidence.requests.push({method:r.request().method(),url:r.url(),status:r.status(),body:body?.slice(0,4000)});});
  await page.goto(widgetUrl+'/');await page.getByRole('button',{name:'Get an estimate'}).click();await page.getByLabel('Service',{exact:true}).selectOption(service.id);await page.getByRole('button',{name:'Continue',exact:true}).click();
  const headings=[];for(let i=0;i<27;i++){
   const heading=await page.locator('form.quote-wizard h2').innerText();headings.push(heading);const field=service.customerFields.find(f=>f.label===heading),value=field&&item.inputs[field.name];
   if(field){if(field.name==='fenceHeight'){await page.getByLabel('Fence height whole feet').fill(value);await page.getByLabel('Fence height inches').fill('0');}else if(field.type==='offering_counts')await page.getByRole('button',{name:'No gates'}).click();else if(value!==undefined){const control=page.getByLabel(field.label,{exact:true});if(['number','string','slug'].includes(field.type))await control.fill(value);else await control.selectOption(value);if(field.type==='slug')await page.getByText('I have identified this exact offering').locator('input').check();}}
   else if(heading==='How can the business reach you?')await page.getByLabel('Email',{exact:true}).fill(item.type.toLowerCase()+'@example.invalid');
   else if(heading==='Where is the work?'){await page.getByLabel('Name',{exact:true}).fill('[SYNTHETIC] Customer');await page.getByLabel('Project location',{exact:true}).fill('[SYNTHETIC] 1 Test Street');await page.getByLabel('City',{exact:true}).fill('Halifax');await page.getByLabel('State / province',{exact:true}).fill('NS');await page.getByLabel('Country',{exact:true}).fill('CA');}
   if(await page.getByRole('button',{name:'Submit estimate request',exact:true}).count())break;await page.getByRole('button',{name:'Continue',exact:true}).click();
  }
  const preparedWait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/public/quote/'+widgetKey+'/prepare'&&r.request().method()==='POST');await page.getByRole('button',{name:'Submit estimate request',exact:true}).click();const preparedResponse=await preparedWait,prepared=await preparedResponse.json();if(preparedResponse.status()!==200||prepared.status!=='ready')throw Error('Prepare '+preparedResponse.status()+': '+JSON.stringify(prepared));
  const quoteWait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/public/quote/'+widgetKey&&r.request().method()==='POST');await page.getByRole('button',{name:'Get estimate',exact:true}).click();const quoteResponse=await quoteWait,result=await quoteResponse.json();const actual=result.pricedEstimate?.midEstimate??result.midEstimate;if(quoteResponse.status()!==201||actual!==item.expected)throw Error('Expected $'+item.expected.toFixed(2)+'; quote '+quoteResponse.status()+': '+JSON.stringify(result).slice(0,6000));return {headings,preparedStatus:prepared.status,resultType:result.resultType,midEstimate:actual,quoteId:result.quoteId,bookingToken:result.bookingToken,screen:(await page.getByRole('dialog').innerText()).slice(-2100)};
 });
 await step('5-booking','Customer slots, hold and confirmed booking',async()=>{
  const quote=evidence.steps.find(s=>s.number==='5-interior_painting')?.actual;if(!quote?.bookingToken)throw Error('No painting quote with booking token');
  for(const [label,value] of Object.entries({Name:'[SYNTHETIC] Customer',Email:'interior_painting@example.invalid',Phone:'+15065550123','Project location':'[SYNTHETIC] 1 Test Street',City:'Halifax','State / province':'NS','Postal / ZIP code':'B3H 0A1',Country:'CA'}))await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByLabel('Have the work or measurements changed since this estimate?').selectOption('UNCHANGED');const path='/api/public/bookings/'+quote.bookingToken+'/availability',wait=page.waitForResponse(r=>new URL(r.url()).pathname===path&&r.request().method()==='POST');await page.getByRole('button',{name:'Book it',exact:true}).click();const response=await wait,availability=await response.json();if(availability.status!=='AVAILABLE'||!availability.slots?.length)throw Error('Availability '+response.status()+' '+JSON.stringify(availability));
  const now=Date.parse(JSON.parse(readFileSync(stateFile,'utf8')).now),blackoutStart=Date.parse('2026-10-12T13:00:00.000Z'),blackoutEnd=Date.parse('2026-10-12T14:00:00.000Z'),busyStart=Date.parse('2026-10-13T13:00:00.000Z'),busyEnd=Date.parse('2026-10-13T14:00:00.000Z');for(const slot of availability.slots){const start=Date.parse(slot.startUtc),end=Date.parse(slot.endUtc);if(start<now+120*60000||!(end<=blackoutStart||start>=blackoutEnd)||!(end+15*60000<=busyStart||start-15*60000>=busyEnd))throw Error('Offered slot violates notice, blackout or busy-event buffer: '+JSON.stringify(slot));}
  await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Review appointment'}).click();await page.getByText('Check your appointment details').waitFor();await page.getByLabel('I confirm this appointment, contact information and job site.').check();const confirmWait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/public/bookings/'+quote.bookingToken+'/confirm'&&r.request().method()==='POST');await page.getByRole('button',{name:'Confirm appointment'}).click();const confirmedResponse=await confirmWait,confirmed=await confirmedResponse.json();if(confirmed.status!=='CONFIRMED')throw Error('Confirmation '+confirmedResponse.status()+' '+JSON.stringify(confirmed));await page.getByText('Site visit booked').waitFor();return {availabilityStatus:response.status(),slotCount:availability.slots.length,firstSlot:availability.slots[0],blackout:'2026-10-12 10:00–11:00 Halifax',noticeMinutes:120,buffersMinutes:15,confirmationStatus:confirmedResponse.status(),appointment:confirmed,calendarFake:JSON.parse(readFileSync(stateFile,'utf8')).calls.slice(-4)};
 });
 await step(6,'Owner dashboard, calendar, leads, quotes and calls after booking',async()=>{
  page=ownerPage;const screens={};for(const [name,url] of [['dashboard','/dashboard'],['calendar','/calendar'],['leads','/leads'],['quotes','/quotes'],['calls','/calls']]){await page.goto(publicUrl+url);await page.locator('main').waitFor();await page.waitForTimeout(200);screens[name]=(await page.locator('main').innerText()).slice(0,5000);await snap('step-6-'+name);}
  const booked=evidence.steps.find(s=>s.number==='5-booking')?.actual?.appointment;const quote=evidence.steps.find(s=>s.number==='5-interior_painting')?.actual;if(!booked)throw Error('Booking did not confirm; owner records cannot be reconciled');if(!screens.calendar.includes('[SYNTHETIC] Customer')||!screens.quotes.includes('$600'))throw Error('Owner calendar/quotes omit customer or $600: '+JSON.stringify(screens).slice(0,6500));if(screens.leads.includes('No saved leads yet.'))throw Error('Widget saved 3 quotes and a booking, but Leads says “No saved leads yet.” Dashboard has 3 quotes and 1 booking.');return {appointmentId:booked.appointmentId,quoteId:quote.quoteId,screens};
 });
 await step(7,'Synthetic staff login and cross-account isolation',async()=>{
  const db=new Database(join(volume,'off-the-clock.sqlite'));const ownerId=evidence.runtime.syntheticBillingSeed[1].ownerId;try{const owner=db.prepare('SELECT * FROM users WHERE id=?').get(ownerId);db.prepare('INSERT INTO users(id,ownerId,email,passwordHash,firstName,businessName,plan,planStatus,trialEndsAt,timezone,role,createdAt,emailVerifiedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(randomBytes(16).toString('hex'),ownerId,'staff@example.invalid',owner.passwordHash,'[SYNTHETIC] Staff',owner.businessName,owner.plan,owner.planStatus,owner.trialEndsAt,owner.timezone,'staff',new Date().toISOString(),new Date().toISOString());}finally{db.close();}
  const staffContext=await browser.newContext({viewport:{width:1440,height:1000}});await staffContext.route(publicUrl+'/**',proxyApplication);page=await staffContext.newPage();await login('staff@example.invalid','SYNTHETIC-Test-Pass-123!');const staff={};for(const [name,url] of [['dashboard','/dashboard'],['calendar','/calendar'],['leads','/leads'],['quotes','/quotes'],['pricebook','/pricebook'],['billing','/settings/billing']]){const response=await page.goto(publicUrl+url);await page.waitForTimeout(150);staff[name]={status:response.status(),text:(await (await page.locator('main').count()?page.locator('main'):page.locator('body')).innerText()).slice(0,12000)};await snap('step-7-staff-'+name);}
  const otherContext=await browser.newContext({viewport:{width:1440,height:1000}});await otherContext.route(publicUrl+'/**',proxyApplication);page=await otherContext.newPage();await login('operator@example.invalid','SYNTHETIC-Test-Pass-123!');const other={};for(const [name,url] of [['dashboard','/dashboard'],['calendar','/calendar'],['leads','/leads'],['quotes','/quotes']]){const response=await page.goto(publicUrl+url);await page.waitForTimeout(150);other[name]={status:response.status(),text:(await (await page.locator('main').count()?page.locator('main'):page.locator('body')).innerText()).slice(0,2400)};await snap('step-7-operator-'+name);}
  if(!staff.calendar.text.includes('[SYNTHETIC] Customer')||!staff.quotes.text.includes('$600'))throw Error('Staff did not see own appointment/quote: '+JSON.stringify(staff).slice(0,4200));if(staff.pricebook.text!=='Forbidden')throw Error('Staff price book not denied: '+JSON.stringify(staff.pricebook));for(const row of Object.values(other))if(row.text.includes('interior_painting@example.invalid')||row.text.includes('[SYNTHETIC] Customer')||row.text.includes('$600'))throw Error('Other owner saw QuoteDone customer record: '+row.text.slice(0,2000));return {staff,other,fixture:'synthetic staff user row with QuoteDone owner link and copied synthetic test password hash; no owner seat invitation route',billingGate:'unverified: billing status API 404 for owner and staff; staff route rendered the generic Billing page'};
 });
 await step(8,'Signed Twilio stream, fake Google mowing quote and duration completion',async()=>{
  const express=(await import('express')).default,WebSocket=(await import('ws')).default,twilio=(await import('twilio')).default;process.env.PRICEBOOK_PATH=join(volume,'pricebooks');process.env.DATABASE_PATH=join(volume,'off-the-clock.sqlite');process.env.JWT_SECRET=env.JWT_SECRET;const {installProductionVoice}=await import('../../server/src/voice/productionVoiceRuntime.js');
  const voiceDb=new Database(join(volume,'off-the-clock.sqlite')),ownerId=evidence.runtime.syntheticBillingSeed[1].ownerId,account='AC'+'a'.repeat(32),token='SYNTHETIC_TWILIO_SIGNING_ONLY',voiceOrigin='https://synthetic-voice.example.invalid',to='+19025550101',from='+19025550100',callSid='CA'+randomBytes(16).toString('hex'),streamSid='MZ'+randomBytes(16).toString('hex');let voice,voiceServer,socket;
  const until=async(predicate,label)=>{const deadline=Date.now()+10000;while(Date.now()<deadline){if(predicate())return;await sleep(10);}throw Error('Timed out waiting for '+label);};
  const responses=new Map(),connections=[],errors=[];let callbacks;const googleClient={live:{connect:async config=>{connections.push(config);callbacks=config.callbacks;return {sendRealtimeInput(){},sendClientContent(){},sendToolResponse(value){for(const item of value.functionResponses)responses.set(item.id,item.response);},async close(){}};}}};
  try{
   voiceDb.prepare("UPDATE businessProfiles SET existingPhoneNumber='+19025550199',twilioNumber=?,twilioNumberSid=?,phoneProvisioningStatus='provisioned',operatorEnabled=1,agentName='Synthetic Nova' WHERE ownerId=?").run(to,'PN'+'a'.repeat(32),ownerId);
   const app=express();voice=installProductionVoice({app,database:voiceDb,bookingService:{},runtimeConfig:{voiceRuntime:true,providerWrites:true},env:{TWILIO_ACCOUNT_SID:account,TWILIO_AUTH_TOKEN:token,PUBLIC_BASE_URL:voiceOrigin,GEMINI_MODEL:'synthetic-live-model',JWT_SECRET:env.JWT_SECRET,VOICE_RUNTIME_ENABLED:'true',ALLOW_PROVIDER_WRITES:'true'},googleClient,clock:()=>new Date(JSON.parse(readFileSync(stateFile,'utf8')).now),onError:code=>errors.push(code)});voiceServer=app.listen(0,'127.0.0.1');await once(voiceServer,'listening');const local='http://127.0.0.1:'+voiceServer.address().port,params={AccountSid:account,CallSid:callSid,From:from,To:to,Direction:'inbound'};
   const post=async(path,body)=>{const signed=twilio.getExpectedTwilioSignature(token,voiceOrigin+path,body);return fetch(local+path,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','x-twilio-signature':signed},body:new URLSearchParams(body)});};
   const incoming=await post('/api/twilio/voice/incoming',params),twiml=await incoming.text(),streamUrl=twiml.match(/<Stream url="([^"]+)"/)?.[1];if(incoming.status!==200||!streamUrl)throw Error('Signed incoming '+incoming.status+': '+twiml+'; errors '+errors);
   socket=new WebSocket(local.replace('http:','ws:')+new URL(streamUrl).pathname,{headers:{'x-twilio-signature':twilio.getExpectedTwilioSignature(token,streamUrl,{})}});await once(socket,'open');socket.send(JSON.stringify({event:'connected',protocol:'Call',version:'1.0.0'}));socket.send(JSON.stringify({event:'start',sequenceNumber:'1',streamSid,start:{accountSid:account,callSid,streamSid,tracks:['inbound'],mediaFormat:{encoding:'audio/x-mulaw',sampleRate:8000,channels:1}}}));await until(()=>connections.length>0,'fake Google connect');
   callbacks.onmessage({serverContent:{inputTranscription:{text:'I need the lawn mowed, 1000 measured square feet, one time, maintained grass, no bagging or edging. I am Synthetic Caller.'}}});const tool=async(name,args)=>{const id='synthetic-'+randomBytes(8).toString('hex');callbacks.onmessage({toolCall:{functionCalls:[{id,name,args}]}});await until(()=>responses.has(id),name+' result');return responses.get(id);};
   const matched=await tool('matchService',{query:'mowing'});if(matched.status!=='matched')throw Error('Voice matchService '+JSON.stringify(matched));const lead=await tool('captureLead',{name:'Synthetic Caller',description:'[SYNTHETIC] One-time lawn mowing',notes:'Caller said 1000 measured square feet, maintained, no bagging or edging.'});if(!lead.status?.startsWith('captured'))throw Error('Voice captureLead '+JSON.stringify(lead));callbacks.onmessage({serverContent:{inputTranscription:{text:'Yes, one thousand square feet. That is right.'},outputTranscription:{text:'Let me get your mowing price.'}}});
   const quoted=await tool('getQuote',{serviceHandle:matched.serviceHandle,customerInputs:{yardSqft:1000,sqftMethod:'exact',serviceFrequency:'one_time',grassCondition:'maintained',bagClippings:false,edgingIncluded:false},customerConfirmed:true});if(quoted.status!=='quoted'||quoted.midEstimate!==100)throw Error('Voice expected $100; '+JSON.stringify(quoted).slice(0,3200));
   socket.send(JSON.stringify({event:'stop',sequenceNumber:'2',streamSid,stop:{accountSid:account,callSid}}));await until(()=>voiceDb.prepare('SELECT status FROM calls WHERE ownerId=? AND callSid=?').get(ownerId,callSid)?.status==='COMPLETED','call completion');const before=voiceDb.prepare('SELECT status,duration,minutesBilled,transcriptJson FROM calls WHERE ownerId=? AND callSid=?').get(ownerId,callSid);
   page=ownerPage;await page.goto(publicUrl+'/calls');await page.locator('.band-count').waitFor();const ownerCallsBefore=(await page.locator('main').innerText()).slice(0,3500);await snap('step-8-before-duration');const completion=await post('/api/twilio/voice/status',{...params,CallStatus:'completed',CallDuration:'125'});const completed=voiceDb.prepare('SELECT status,duration,minutesBilled,transcriptJson FROM calls WHERE ownerId=? AND callSid=?').get(ownerId,callSid);await page.reload();await page.locator('.band-count').waitFor();const ownerCallsAfter=(await page.locator('main').innerText()).slice(0,3500);await snap('step-8-after-duration');await page.goto(publicUrl+'/leads');await page.getByText(/Synthetic Caller/).first().waitFor();const ownerLeads=(await page.locator('main').innerText()).slice(0,3500);await snap('step-8-leads');await page.goto(publicUrl+'/quotes');await page.getByText(/\$100/).first().waitFor();const ownerQuotes=(await page.locator('main').innerText()).slice(0,3500);await snap('step-8-quotes');
   if(completion.status!==204||completed.minutesBilled!==3||before.minutesBilled!==0||!ownerCallsAfter.includes('Synthetic Caller')||!ownerLeads.includes('Synthetic Caller')||!ownerQuotes.includes('$100'))throw Error('Voice record mismatch '+JSON.stringify({completion:completion.status,before:{status:before.status,minutesBilled:before.minutesBilled},after:{status:completed.status,minutesBilled:completed.minutesBilled},screens:{calls:ownerCallsAfter,leads:ownerLeads,quotes:ownerQuotes},errors}).slice(0,6500));return {fake:'test/voiceQuotePathCases20261005.mjs provider() Google live session and signed Twilio WebSocket/status shape',twiml:twiml.slice(0,1100),callSid,matchedStatus:matched.status,leadStatus:lead.status,quotedAmount:quoted.midEstimate,before:{status:before.status,minutesBilled:before.minutesBilled,transcript:before.transcriptJson},completionStatus:completion.status,after:{status:completed.status,minutesBilled:completed.minutesBilled},ownerCallsBefore,ownerCallsAfter,ownerLeads,ownerQuotes,errors};
  }finally{socket?.terminate();await voice?.close();voiceServer?.closeAllConnections?.();if(voiceServer)await new Promise(r=>voiceServer.close(r));voiceDb.close();}
 });
 await step(9,'Trial billing page without live Stripe',async()=>{page=ownerPage;await page.goto(publicUrl+'/settings/billing');await page.getByRole('heading',{name:'Billing',exact:true}).waitFor();await page.waitForTimeout(300);const body=await page.locator('main').innerText(),status=evidence.requests.findLast(r=>new URL(r.url).pathname==='/api/billing/status');if(status?.status!==200)throw Error('Billing status '+status?.status+' '+status?.body+'; screen: '+body);return {screen:body,status};});
}finally{if(browser)await browser.close();await stop();writeEvidence();}
