export const CREATE_TABLE_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    firstName TEXT NOT NULL,
    businessName TEXT NOT NULL,
    plan TEXT NOT NULL DEFAULT 'Operator',
    planStatus TEXT NOT NULL DEFAULT 'trialing',
    trialEndsAt TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    role TEXT NOT NULL CHECK (role IN ('owner', 'staff', 'admin')),
    createdAt TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS calls (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    callSid TEXT,
    callerNumber TEXT,
    duration INTEGER,
    outcome TEXT,
    transcriptJson TEXT,
    summaryText TEXT,
    urgency TEXT,
    spamFiltered INTEGER NOT NULL DEFAULT 0,
    minutesBilled INTEGER NOT NULL DEFAULT 0,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS leads (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    callId TEXT,
    customerName TEXT,
    callerNumber TEXT,
    describedService TEXT,
    collectedInputsJson TEXT,
    type TEXT,
    status TEXT,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id),
    FOREIGN KEY (callId) REFERENCES calls(id)
  )`,
  `CREATE TABLE IF NOT EXISTS quoteRequests (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    callId TEXT,
    describedService TEXT,
    estimatedValue INTEGER,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id),
    FOREIGN KEY (callId) REFERENCES calls(id)
  )`,
  `CREATE TABLE IF NOT EXISTS quotes (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    callId TEXT,
    quoteId TEXT,
    serviceType TEXT,
    customerInputsJson TEXT,
    resultJson TEXT,
    tierChosen TEXT,
    status TEXT,
    finalInvoiceAmount INTEGER,
    pageToken TEXT,
    pageExpiresAt TEXT,
    callerType TEXT,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id),
    FOREIGN KEY (callId) REFERENCES calls(id)
  )`,
  `CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    phoneE164 TEXT,
    name TEXT,
    address TEXT,
    notesJson TEXT,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS appointments (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    customerId TEXT,
    quoteId TEXT,
    serviceType TEXT,
    bookingMode TEXT,
    datetime TEXT,
    durationMinutes INTEGER,
    status TEXT,
    depositRequested INTEGER NOT NULL DEFAULT 0,
    depositPaid INTEGER NOT NULL DEFAULT 0,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id),
    FOREIGN KEY (customerId) REFERENCES customers(id),
    FOREIGN KEY (quoteId) REFERENCES quotes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    ownerId TEXT NOT NULL,
    eventType TEXT NOT NULL,
    payloadJson TEXT,
    createdAt TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES users(id)
  )`
];
