// Synthetic owner-entered DOLLAR prices and measured customer facts. Expectations
// below were written before adapter execution. No engine-derived approvals,
// identity receipts, calculation helpers or price converters are used here.
export const adapterCases=[
 ['ROOFING_REPLACEMENT',{laborPerSquare:{asphalt_shingle:50},materialCostPerSquare:{asphalt_shingle:100},tearOffPerSquare:{asphalt_shingle:20},underlaymentPerSquare:{asphalt_shingle:15},underlaymentPriceBasis:{asphalt_shingle:'installed_area_sell_price'},accessoryPricingMode:'itemized',materialAccessoryBasis:'excludes_itemized_accessories',starterPerLF:1,dripEdgePerLF:2,ridgeCapPerLF:3,deckingPerSheet:50,minimumJob:0},{roofSizeMethod:'roof_measured',roofSizeInput:1000,existingRoofType:'asphalt_shingle',replacementRoofType:'asphalt_shingle',pitch:'low',stories:1,existingLayers:1,roofComplexity:'simple',serviceScope:'full',starterLengthLF:100,dripEdgeLengthLF:100,ridgeCapLengthLF:20,deckingSheets:2},241000,'10×50 + 11×100 + 10×20 + 10×15 + 100×1 + 100×2 + 20×3 + 2×50 = $2410','roofSizeInput'],
 ['ROOFING_REPAIR',{laborHourlyRate:100,repairMinimum:0,repairHours:{asphalt_shingle:{patch:{small:2,medium:4,large:8}}},repairMaterialAllowance:{asphalt_shingle:{patch:{small:40,medium:80,large:160}}}},{repairType:'patch',affectedArea:100,roofType:'asphalt_shingle',pitch:'medium',stories:2,leakPresent:false},58600,'4 hours×$100×1.15×1.10 + $80 = $586','affectedArea'],
 ['FLAT_ROOF_REPLACEMENT',{laborPerSqft:{epdm:5},membraneCostPerSqft:{epdm:7},tearOffPerSqft:{epdm:2},minimumJob:0},{roofSqft:1000,sqftMethod:'exact',membraneType:'epdm',replacementMembraneType:'epdm',existingLayers:2,accessDifficulty:'moderate',serviceScope:'full',buildingType:'residential'},1735000,'1000×5×1.15 + 1000×7 + 1000×2×2×1.15 = $17350','roofSqft'],
 ['FLAT_ROOF_REPAIR',{laborHourlyRate:100,repairMinimum:0,patchRepairHours:{epdm:{patch:{small:3,medium:5,large:8}}},patchMaterialAllowance:{epdm:{patch:{small:60,medium:90,large:140}}}},{repairType:'patch',affectedArea:10,membraneType:'epdm',leakPresent:false,pondingWater:false},36000,'3 hours×$100 + $60 = $360','affectedArea'],
 ['INTERIOR_PAINTING',{laborPerWallSqftPerCoat:1,materialPerWallSqftPerCoat:0.3,minimumJob:0,ceilingLaborPerSqftPerCoat:1,ceilingMaterialPerSqftPerCoat:0.3,trimLaborPerLF:1.25,trimMaterialPerLF:0.5},{areaInputMethod:'wall_sqft',wallAreaSqft:500,wallHeight:'standard',wallScopeUniform:true,surfaceCondition:'good',coats:2,ceilingsIncluded:false,trimIncluded:true,trimLengthLF:200},165000,'500×2×(1+.30) + 200×(1.25+.50) = $1650','wallAreaSqft'],
 ['EXTERIOR_PAINTING',{exteriorLaborPerSqftPerCoat:1,materialPerSqftPerCoat:0.5,minimumJob:0,laborHourlyRate:100},{areaInputMethod:'wall_sqft',exteriorAreaSqft:1000,stories:2,surfaceCondition:'fair',coats:2},null,'Review: exterior substrate/coating/preparation model remains unresolved','exteriorAreaSqft'],
 ...['FLOORING_INSTALL','FLOORING_REPLACEMENT'].map(t=>[t,{laborPerSqft:{vinyl_plank:3},materialPerSqft:{vinyl_plank:5},minimumJob:0,vinylPlankUnderlaymentRule:'never_included',roomSizeThresholds:{smallMaxSqft:149,mediumMaxSqft:299}},{sqft:300,sqftMethod:'exact',newFlooringType:'vinyl_plank',existingFloorType:'none',removalNeeded:false,roomCount:1,layoutPattern:'straight',stairSteps:0,...(t==='FLOORING_REPLACEMENT'?{subfloorIssues:false}:{})},252000,'300×$3 + 300×1.08×$5 = $2520; average room300 above299','sqft']),
 ...['FENCING_INSTALL','FENCING_REPLACEMENT'].map(t=>[t,{laborPerLinearFoot:{wood:10},materialPerLinearFoot:{wood:20},postPrice:{wood:25},concretePerPost:7,postsIncludedInMaterial:{wood:false},gatePrice:{wood:250},minimumJob:0},{linearFeet:100,lfMethod:'exact',fenceType:'wood',fenceHeight:6,gateCount:0,terrainSlope:'flat',...(t==='FENCING_REPLACEMENT'?{oldFenceRemoval:false}:{})},null,'Review: mixed concrete/digging category and post geometry remain unresolved','linearFeet']),
 ['CONCRETE_DRIVEWAY',{laborPerSqft:6,concreteCostPerCubicYard:180,formworkPerLF:25,minimumJob:0,basePrepPerSqft:1.75,wireReinforcementPerSqft:1.5},{dimensionMethod:'exact',length:50,width:10,thickness:4,finishType:'broom',demolitionNeeded:false,reinforcement:'wire_mesh',accessDifficulty:'easy',baseNeeded:true},884722,'500×6 + roundCent((500×4/12/27)×1.10×180) + 120×25 + 500×1.75 + 500×1.50 = $8847.22','length'],
 ['CONCRETE_PATIO_SLAB',{laborPerSqft:6,concreteCostPerCubicYard:180,formworkPerLF:25,minimumJob:0,basePrepPerSqft:1.75},{dimensionMethod:'exact',length:20,width:10,thickness:4,finishType:'broom',demolitionNeeded:false,reinforcement:'none',accessDifficulty:'easy',baseNeeded:true},353889,'200×6 + roundCent((200×4/12/27)×1.10×180) + 60×25 + 200×1.75 = $3538.89','length'],
 ['LANDSCAPING_CLEANUP',{cleanupBaseRatePerSqft:0.1,debrisPricing:{light:{laborMultiplier:1,disposalFlat:50},moderate:{laborMultiplier:1.5,disposalFlat:100},heavy:{laborMultiplier:2,disposalFlat:150}},minimumServiceCharge:0,haulAwayFee:50},{yardSqft:1000,sqftMethod:'exact',debrisLevel:'heavy',slope:'flat',haulAway:true},40000,'1000×.10×2 +150 +50 = $400','yardSqft'],
 ['LANDSCAPING_MULCH',{mulchMaterialPerYard:{brown:50},mulchInstallLaborPerYard:30,minimumServiceCharge:0,bedPrepLaborPerSqft:{needs_weeding:.2,overgrown:.4},edgingPerLinearFoot:.5},{inputMethod:'sqft',mulchArea:270,mulchDepth:3,mulchType:'brown',bedCondition:'needs_weeding',bedSqft:270,edgingNeeded:true,edgeLF:100},32275,'270×.20 + (270×3/12/27)×1.15×50 + 2.5×30 +100×.50 = $322.75','mulchArea'],
 ['LANDSCAPING_SOD',{sodMaterialPerSqft:.75,sodInstallLaborPerSqft:1.25,minimumServiceCharge:0,groundPrepPerSqft:.5},{sodSqft:1000,sqftMethod:'exact',groundPrepNeeded:true,slope:'flat',accessDifficulty:'easy'},253750,'1000×1.05×.75 +1000×1.25 +1000×.50 = $2537.50','sodSqft'],
 ['LANDSCAPING_PLANTING',{plantingLaborPerPlant:{small:10,medium:20,large:30},plantMaterialAllowance:{small:5,medium:10,large:15},minimumServiceCharge:0,bedPrepLaborPerSqft:{needs_weeding:.2,overgrown:.4},mulchMaterialPerYard:{brown:50},mulchInstallLaborPerYard:30},{plantsBySize:{small:2,medium:1,large:1},bedCondition:'needs_weeding',bedSqft:100,mulchNeeded:true,mulchYards:2,mulchType:'brown'},30000,'2×(10+5)+(20+10)+(30+15)+100×.2+2×1.15×50+2×30=$300','plantsBySize'],
 ['LANDSCAPING_MOWING',{mowingBaseRatePerSqft:.02,minimumServiceCharge:0,frequencyMultipliers:{weekly:1,biweekly:1.2,monthly:1.5,one_time:1.8},overgrowthMultipliers:{maintained:1,overgrown:1.5,severe:2},baggingSurchargePercent:10,edgingPerLinearFoot:.5},{yardSqft:5000,sqftMethod:'exact',serviceFrequency:'weekly',grassCondition:'maintained',bagClippings:true,edgingIncluded:true,edgingLengthLF:100},16000,'5000×.02 +10%×100 +100×.50 = $160','yardSqft'],
 ['SIDING_REPLACEMENT',{laborPerSqft:{vinyl:4},materialPerSqft:{vinyl:7},minimumJob:0},{areaInputMethod:'sqft',sidingAreaSqft:1000,sidingType:'vinyl',stories:1,oldSidingRemoval:false,trimIncluded:false},1170000,'1000×4 +1000×1.10×7 = $11700','sidingAreaSqft'],
 ['SIDING_REPAIR',{laborHourlyRate:100,repairMinimum:0,repairHours:{vinyl:{minor:{small:2,medium:4,large:8}}},materialAllowance:{vinyl:{minor:{small:50,medium:100,large:200}}}},{sidingType:'vinyl',damageLevel:'minor',affectedArea:50,stories:2},54000,'4×100×1.10 +100 = $540','affectedArea'],
 ['CUSTOM',{customPricingMode:'fixed',price:100,unit:'per_hour',minimumJob:0},{hours:2,unit:'per_hour'},null,'Review: measured and bounded custom scope contract unresolved','hours']
].map(([serviceType,pricing,customerInputs,expectedCents,derivation,requiredMeasurement])=>({serviceType,pricing,customerInputs,expectedCents,derivation,requiredMeasurement}));
